# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'MimiImg' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MimiImg
  pod 'SVProgressHUD'
  pod 'AFNetworking'
  pod 'MJRefresh'
  pod 'ReactiveCocoa',2.5
  pod 'BlocksKit'
  pod 'IQKeyboardManager', '~>5.0'
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'Motis'
  pod 'YYModel'
  pod 'KLCPopup'
  pod 'TZImagePickerController', '~> 1.9.8'
  pod 'RDVTabBarController'
end
